<a href="https://colab.research.google.com/github/AmeliaReginaa/pemograman-lanjutan/blob/main/matriks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. PENGANTAR MATRIKS
Pada dasarnya adalah array 2 dimensi.Matriks dapat di deklarasikan dengan:


In [ ]:
A = [[0 for j in range(20)] for i in range (10)]
A

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]

Untuk elemen baris ke-i dan kolom ke-j perlu diakses dengan A[i-1] [j-1] karena indeks matriks dimulai dari 0.

In [ ]:
n = input(input())
m = input(input())

A = [[0 for j in range(m)] for i in range(n)]

for i in range(n):
  for j in range(m):
    A[i][j] = int(input("masukan elemen baris"+str(i+1)+"kolom"+str(j+1)+":"))
    for i in range(n):
      for j in range(m):
        print(A[i][j],end="")
        print("")

In [ ]:
for i in range(n):
  for j in range (m):
    print(A[i][j], end="")
    print("")

In [ ]:
n = int(input())
m = int(input())
i = int(input())

A = [[0 for j in range(m)] for i in range(n)]
B = [[O for j in range(i)] for i in range(m)]
C = [[0 for j in range(i)]for i in range(n)]

for i in range(n):
  for j in range(m):
    A[I]


MATRIKS DENGAN LIBRARY NUMPY

In [ ]:
import numpy as np
x1 = np.array([[2,3,4],
              [2,5,6],
              [6,7,8]])
x1

array([[2, 3, 4],
       [2, 5, 6],
       [6, 7, 8]])

MATRIKS DENGAN LIST

In [ ]:
ls = [[2,3,4],
         [2,5,6],
         [6,7,8]]
ls


[[2, 3, 4], [2, 5, 6], [6, 7, 8]]

In [ ]:

x2 = np.dot(x1,x1)
x2

array([[ 34,  49,  58],
       [ 50,  73,  86],
       [ 74, 109, 130]])

**LATIHAN MODUL 4 **

SEGITIGA PASCAL

In [ ]:
n = 5

segitiga = [[1] * (i + 1) for i in range(n)]

for i in range(2, n):
    for j in range(1, i):
        segitiga[i][j] = segitiga[i - 1][j - 1] + segitiga[i - 1][j]

for baris in segitiga:
    print(baris)

[1]
[1, 1]
[1, 2, 1]
[1, 3, 3, 1]
[1, 4, 6, 4, 1]


2.2 LINEAR ALGEBRA

A. Tentukan determinan dari matriks berikut
A = [1 2]
    

In [ ]:
import numpy as np

# Tentukan Determinan
# Matriks A
A = np.array([[1, 2],
              [3, 4]])

# Matriks B
B = np.array([[-1, 3, 0],
              [2, 1, -5],
              [1, 4, -2]])

# Menghitung determinan
det_A = np.linalg.det(A)
det_B = np.linalg.det(B)

print("Determinan matriks A:", round(det_A))
print("Determinan matriks B:", round(det_B))

Determinan matriks A: -2
Determinan matriks B: -21


B. TENTUKAN TRANSPOSE DARI MATRIKS

In [ ]:
# Matriks A untuk transpose
A_transpose = np.array([[1, 3, 7, 2],
                        [5, 8, -9, 0],
                        [6, -7, 11, 12]])

# Menghitung transpose
transpose_A = A_transpose.T

print("Transpose matriks A:")
print(transpose_A)

Transpose matriks A:
[[ 1  5  6]
 [ 3  8 -7]
 [ 7 -9 11]
 [ 2  0 12]]
